version: '3.8'
name: cleanarchitecture

services:

  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "11002:80"
  
  architecture:
    image: structurizr/lite:latest
    ports:
      - 11003:8080
    volumes:
      - ../Architecture:/usr/local/structurizr