name: Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SOLUTION_FILE: ./src/AggregateGroot.Sdk.sln

    steps:

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore $SOLUTION_FILE

    - name: Build
      run: dotnet build $SOLUTION_FILE --no-restore -c Release

    - name: Test
      run: dotnet test $SOLUTION_FILE --no-restore --no-build -c Release

    - name: Pack Solution
      run: dotnet pack $SOLUTION_FILE -c Release

    - name: Push Packages
      run: dotnet nuget push src/**/bin/**/*.nupkg --api-key ${{ secrets.NUGET_PUBLISH_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
